start of 2022 restructure
UWindsorCSS/Documents pull request #6
Opened 2022-02-24 12:31 UTC by jere-mie

This is the start of the 2022 restructure of the constitution.

It is ready to review but not ready to merge.

2022-02-24 15:29 UTC, prairir requested changes

2022-02-24 15:29 UTC, prairir commented on constitution.md
> +2. Be appointed via interview process, conducted by executive Computer Science Society executives.
remove the first `executive`

2022-02-24 15:29 UTC, prairir commented on constitution.md
> +4. Be responsible for managing the Computer Science Discord including channels, bots, roles, etc.
I think adding a `Be responsible for all future CSS technology endeavours` or something similar is a good idea

2022-02-24 15:29 UTC, prairir commented on constitution.md
> +4. Be responsible for managing the Computer Science Discord including channels, bots, roles, etc.
not to mention act as a moderator

2022-02-24 15:29 UTC, prairir commented on constitution.md
> +8. Be responsible for overseeing the communications team (i.e., Head of Communications)
```suggestion
8. Be responsible for overseeing the communications team (i.e., Head of Communications).
```

2022-02-24 15:29 UTC, prairir commented on constitution.md
>  1. Report to the President
Some( but not all) of these `Report to <name>` sentences dont have `.` at the end but all other lines do. Not sure what to do, just wanna be consistent

2022-02-24 15:29 UTC, prairir commented on constitution.md
> +2. Be responsible for leading the Communications team (i.e., Merchandising Coordinator, Promotions Coordinator, Design Coordinator)
```suggestion
2. Be responsible for leading the Communications team (i.e., Merchandising Coordinator, Promotions Coordinator, Design Coordinator).
```

2022-02-24 15:29 UTC, prairir commented on constitution.md
> +5. Host/organize any design contests with the students (e.g., sweater design contest)
```suggestion
5. Host/organize any design contests with the students (e.g., sweater design contest).
```

2022-02-24 15:30 UTC, prairir commented
Its overall pretty good. There are some grammatical inconsistencies that Id like resolved first.

2022-02-24 16:00 UTC, Sharjeeliv reviewed
A pretty solid update, we should work on making it more consistent (grammar, formality, pov, etc.). Consider explicitly stating who each role is expected to collaborate with and the nature of their collaboration.

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
>  4. Be the final say in which events we will host and create polls if we want the students to decide which events they want.
Could be reworded to be more formal ie. Be the final say in which events the CSS will host and create polls if the CSS determines that students should decide which events they want.

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
>  5. Be responsible for posting events on the CSS website, Discord, and email and work with the Social Media Coordinator to advertise on social media
Should be adjusted for the new promotions coordinator role. Decide if promotion activities (Posting on CSS website, Discord, etc.) should be done by the promotions cord and the Head of Events is responsible to communicate and work with the promotions cord to accomplish this goal.

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
>  The **Head of Events** shall:
Should add a point that the Head of Events should collaborate with the head of Comms to plan for events, promos, communications, etc.

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
> +
The Head of Student Affairs should also be responsible for overseeing the reps and career advisor, be responsible for planning and executing strategies to develop student skills, collaborate with the Head of events to determine events that would benefit students (workshops to prepare for interviews, coop, teach skills, prepare for courses etc.)

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
> +5. Host/organize any design contests with the students (e.g., sweater design contest)
Should add a section that the merch cord collaborates with the design cord to come up with merch designs. Merch cord collaborates with promo cord to effectively promote a merch run. In some sections, we explicitly say certain positions should collaborate/manage while others we do not we should fix the inconsistencies. It might be best to clearly state what other positions a role is expected to collaborate with and the nature of their collaboration

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
> +
The promotions cord is also responsible for all "offline" promotions (posters, flyers, etc) as well. The term promoting would fit better than marketing. And on line 3 instead of social media channels, it should be communication channels (encompass socials and more)

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
>  4. Be responsible for photographing or recording events to post on social media and share the photographs/videos with the Social Media Coordinator.
Update to promo cord

2022-02-24 16:00 UTC, Sharjeeliv commented on constitution.md
> +The **Design Coordinator** shall:
We should add that they are expected to follow the CSS branding style to develop assets.

2022-02-28 21:34 UTC, prairir approved these changes

2022-03-03 02:41 UTC, benchittle requested changes
Looks good overall! Here's a bunch of minor changes to keep grammar a bit more consistent.

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +2. Shall act in the place of the President, where conflicts prohibit the president from acting or the president is unable to act.
```suggestion
2. Act in the place of the President, where conflicts prohibit the president from acting or the president is unable to act.
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
>  The **CSC Liaison(s)** Shall:
```suggestion
The **CSC Liaison(s)** shall:
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +5. Collaborate with the Head of Events to determine events that would benefit students (i.e., workshops to prepare for interviews, co-op, teach skills, prepare for courses, etc.)
```suggestion
5. Collaborate with the Head of Events to determine events that would benefit students (e.g., workshops to prepare for interviews, co-op, teach skills, prepare for courses, etc.).
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
>  2. Be responsible for communicating with venues to organize, schedule, and gather pricing events.
```suggestion
2. Be responsible for communicating with venues to organize, schedule, and gather pricing for events.
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
>  3. Be in constant communication with the Head of Events to help arrange and organize the events, as well as organizing the payment method in an organized fashion.
```suggestion
3. Be in constant communication with the Head of Events to help arrange and organize the events, as well as any necessary payments.
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
>  3. Be responsible for representing the executive to second year members of the Society.
```suggestion
3. Be responsible for representing the executive to second-year members of the Society.
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +3. Be responsible for representing the executive to all first year members of the Society.
```suggestion
3. Be responsible for representing the executive to all first-year members of the Society.
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +3. Be responsible for representing the executive to all third and fourth year members of the Society.
```suggestion
3. Be responsible for representing the executive to all third- and fourth-year members of the Society.
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
>  The first year representative, and any positions not elected in the
```suggestion
The first-year representative, and any positions not elected in the
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +12. Second Year Representative
```suggestion
12. Second-Year Representative
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +13. First Year Representative (2)
```suggestion
13. First-Year Representative (2)
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +2. Be responsible for leading the Student Affairs team (i.e., Career Advisor, Senior Representative, Second Year Representative, First Year Representative(s)).
```suggestion
2. Be responsible for leading the Student Affairs team (i.e., Career Advisor, Senior Representative, Second-Year Representative, First-Year Representative(s)).
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
> +The **First Year Representative(s)** shall:
```suggestion
The **First-Year Representative(s)** shall:
```

2022-03-03 02:41 UTC, benchittle commented on constitution.md
>  The **Second Year Representative** shall:
```suggestion
The **Second-Year Representative** shall:
```

2022-03-08 00:43 UTC, merged